[2024-10-21T16:56:43.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-21T16:56:43.996+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_principal.python_principal scheduled__2023-06-29T20:00:00+00:00 [queued]>
[2024-10-21T16:56:44.019+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_principal.python_principal scheduled__2023-06-29T20:00:00+00:00 [queued]>
[2024-10-21T16:56:44.029+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-21T16:56:44.129+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): python_principal> on 2023-06-29 20:00:00+00:00
[2024-10-21T16:56:44.143+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=134) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-21T16:56:44.145+0000] {standard_task_runner.py:72} INFO - Started process 166 to run task
[2024-10-21T16:56:44.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_principal', 'python_principal', 'scheduled__2023-06-29T20:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/lesson_3_dag_principal.py', '--cfg-path', '/tmp/tmpsddkdlix']
[2024-10-21T16:56:44.158+0000] {standard_task_runner.py:105} INFO - Job 74: Subtask python_principal
[2024-10-21T16:56:44.330+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_principal.python_principal scheduled__2023-06-29T20:00:00+00:00 [running]> on host 1da8eee663cb
[2024-10-21T16:56:44.554+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='DAG_principal' AIRFLOW_CTX_TASK_ID='python_principal' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-29T20:00:00+00:00'
[2024-10-21T16:56:44.557+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-21T16:56:44.558+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-21T16:56:44.562+0000] {logging_mixin.py:190} INFO - Current task name:python_principal state:running start_date:2024-10-21 16:56:43.997404+00:00
[2024-10-21T16:56:44.564+0000] {logging_mixin.py:190} INFO - Dag name:DAG_principal and current dag run status:running
[2024-10-21T16:56:44.564+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-21T16:56:44.568+0000] {logging_mixin.py:190} INFO - DAG principal
[2024-10-21T16:56:44.573+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lesson_3_dag_principal.py", line 11, in print_principal
    pprint.pring(kwargs)
    ^^^^^^^^^^^^
AttributeError: module 'pprint' has no attribute 'pring'. Did you mean: 'pprint'?
[2024-10-21T16:56:44.624+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-21T16:56:44.625+0000] {logging_mixin.py:190} INFO - Task start:2024-10-21 16:56:43.997404+00:00 end:2024-10-21 16:56:44.623339+00:00 duration:0.625935
[2024-10-21T16:56:44.627+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): python_principal> dag:<DAG: DAG_principal> dagrun:<DagRun DAG_principal @ 2023-06-29 20:00:00+00:00: scheduled__2023-06-29T20:00:00+00:00, state:running, queued_at: 2024-10-21 16:56:37.574463+00:00. externally triggered: False>
[2024-10-21T16:56:44.628+0000] {logging_mixin.py:190} INFO - Failure caused by module 'pprint' has no attribute 'pring'
[2024-10-21T16:56:44.629+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=DAG_principal, task_id=python_principal, run_id=scheduled__2023-06-29T20:00:00+00:00, execution_date=20230629T200000, start_date=20241021T165643, end_date=20241021T165644
[2024-10-21T16:56:44.646+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-21T16:56:44.648+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 74 for task python_principal (module 'pprint' has no attribute 'pring'; 166)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lesson_3_dag_principal.py", line 11, in print_principal
    pprint.pring(kwargs)
    ^^^^^^^^^^^^
AttributeError: module 'pprint' has no attribute 'pring'. Did you mean: 'pprint'?
[2024-10-21T16:56:44.688+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-21T16:56:44.721+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-21T16:56:44.734+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
